### ISSUE TITLE
Two image links (cheat sheets in entries.adoc) don't work after publication

### ISSUE THREAD

**Issue by espen42** [enonic/demo-react4xp#1]
docs/entries.adoc has two image links...

```
media/entries_cheatsheet.png
media/entries_howto.png
```

...that don't work at https://developer.enonic.com/templates/react4xp/master/entries (they give "_404 - not found"_) even though they work locally.

**Comment by espen42** [comment]
@sigdestad , @poi33 : fix is published at [the entries page](https://developer.enonic.com/docs/react4xp/master/entries), follow the two cheat sheet links to https://developer.enonic.com/docs/react4xp/master/entries_cheatsheet and https://developer.enonic.com/docs/react4xp/master/entries_howto .

Ideally I'd like to remove the ToC on the right, it's pointless here and it's just a good thing if the image can get even bigger. Haven't found out how, yet.

**Comment by poi33** [comment]
What are you trying to do? 
Have a downloudable link to a image? inside the doc?

**Comment by espen42** [comment]
Yes, exactly.

**Comment by poi33** [comment]
Adding a downloud link is somthing that asciidoctor does not support. 
A simple workaround is adding the image to the developer site. 
Just create a downloud folder on our developer site and publish the image. Then use that link in the docs.

**Comment by espen42** [comment]
Any workaround seems just as hacky or more, than this one. I'll just keep it as it is now, with the cheat sheet pages mentioned above.
